name: tadweer_alkheer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.1+18


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^1.0.4
  auto_size_text: ^2.1.0
  #cloud_firestore_web: ^0.3.0
  firebase_auth: ^1.0.3
  dio:
# image_picker: ^0.8.4+10
  firebase_storage: ^8.0.3
  provider: ^6.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_localized_locales: ^2.0.0
  dropdown_button2: ^1.4.0
  custom_timer: ^0.0.3
  intl_phone_field: ^2.0.1
  geolocator: ^8.0.0
  image_picker: ^0.8.5+3
  otp_text_field: ^1.1.1
  location: ^4.3.0
  flutter_native_splash: ^1.3.2
  plugin_platform_interface: ^2.0.0
  location_web:
  top_snackbar_flutter: ^0.0.3
  google_maps_flutter: ^2.1.2
  http: ^0.13.3
 # http_parser: ^3.1.3
 # path_provider: ^2.0.9
  splash_screen_view: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  curved_navigation_bar: ^1.0.3
  flutter_rating_bar: ^4.0.0
  rating_dialog: ^2.0.3
  store_redirect: ^2.0.0
  convex_bottom_bar: ^3.0.0
  launch_review: ^3.0.1
  lottie: ^1.2.2
  animated_splash_screen: ^1.2.0
  flutter_local_notifications:
  splashscreen: ^1.3.5
  cupertino_icons: ^1.0.2
  video_player: ^2.2.19
  video_player_web: ^2.0.4
  firebase_messaging: ^11.2.8
  path_provider:
  firebase_core: ^1.3.3
  shared_preferences: ^2.0.13
  video_thumbnail: ^0.4.6
  share: ^2.0.4
  onboarding: ^3.1.0
  photo_view: ^0.13.0
  firebase_core_platform_interface: 4.5.1
  smooth_page_indicator: ^1.0.0+2
  chewie: ^1.1.0
  url_launcher: ^6.0.2
  rate_my_app: ^1.1.2
  carousel_slider: ^4.1.1
  fluttertoast: ^8.1.1
  #contactus: ^1.2.0
 # flutter_screenutil: ^5.3.1
  sizer: ^2.0.15
  #new_version_plus: ^0.0.1+4
  new_version: ^0.3.1
  flutter_polyline_points: ^1.0.0
  csc_picker: ^0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
#flutter_native_splash: ^1.2.3

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/new_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/new_logo.png"

flutter_native_splash:
  image: assets/logo.png
  color: "#1d89e0"
  android_gravity: center
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  # color: "#FF0000"

 # background_image: assets/images/splash_bg.png
 # android: true
 # ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: fonts/ElMessiri.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: fonts/Tajawal-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
